language: objective-c
osx_image: xcode8.1
rvm:
- 2.2
before_install:
- chmod a+x ./City\ Chunks/install.sh
- chmod a+x ./City\ Chunks/build.sh
install:
- ./City\ Chunks/install.sh
script:
- ./City\ Chunks/build.sh
